import {StrictMode} from 'react';
import {createRoot} from 'react-dom/client';
import App from './App.tsx';
import './index.css';

// Filter out harmless cross-origin "Script error." logs generated by high-security sandboxed iframes or extensions
if (typeof window !== 'undefined') {
  const originalOnError = window.onerror;
  window.onerror = function (message, source, lineno, colno, error) {
    const msg = String(message || "").toLowerCase();
    if (msg.includes("script error") || msg.includes("unexpected token") || !source) {
      console.warn("Filtered cross-origin iframe/extension script warning:", message, "from:", source);
      return true; // Stop event from bubble-alert propagation
    }
    if (originalOnError) {
      return originalOnError(message, source, lineno, colno, error);
    }
    return false;
  };

  window.addEventListener('unhandledrejection', (event) => {
    const reason = event.reason;
    if (reason && (String(reason).includes("Script error") || String(reason).includes("NetworkError"))) {
      console.warn("Filtered cross-origin promise rejection warning:", reason);
      event.preventDefault();
    }
  });
}

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
);
